language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
#install:
#  - "pip install . --use-mirrors"
#  - "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: py.test --doctest-modules
